[package]
authors = ["Frank Denis <github@pureftpd.org>"]
keywords = ["data-structures"]
license = "MIT/Apache-2.0"
name = "arc-cache"
repository = "https://github.com/jedisct1/arc-cache"
version = "0.2.0"

[dependencies.lru-cache]
git = "https://github.com/jedisct1/lru-cache.git"
